//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcCauldronCapo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int ALERT_ID { get; set; }
        public string ALERT_TEXT { get; set; }
        public System.DateTime EXPIRES_DT_TM { get; set; }
        public string SECTION { get; set; }
    }
}
