//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcCauldronCapo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANT_HISTORY
    {
        public int CHANT_HISTORY_ID { get; set; }
        public int CHANT_ID { get; set; }
        public System.DateTime DATE_PLAYED_DT_TM { get; set; }
    
        public virtual CHANT CHANT { get; set; }
    }
}
