//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcCauldronCapo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENT_VOTES
    {
        public int CHANT_ID { get; set; }
        public Nullable<double> CHANT_COUNT { get; set; }
        public string CHANT_NAME { get; set; }
        public Nullable<double> COUNT { get; set; }
        public string PERCENT { get; set; }
    }
}
