//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcCauldronCapo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hackathon_TestEntities : DbContext
    {
        public Hackathon_TestEntities()
            : base("name=Hackathon_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChantHistory> ChantHistories { get; set; }
        public DbSet<Chant> CHANTS { get; set; }
        public DbSet<User> Users1 { get; set; }
        public DbSet<Vote> VOTES { get; set; }
        public DbSet<CURRENT_DAY_USERS> CURRENT_DAY_USERS { get; set; }
        public DbSet<CURRENT_VOTES> CURRENT_VOTES { get; set; }
        public DbSet<Alert> ALERTS { get; set; }
    }
}
