//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KcCauldronCapo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SUBMITTED_IDEAS
    {
        public int USER_SUBMITTED_IDEAS_ID { get; set; }
        public int USER_ID { get; set; }
        public string LYRICS { get; set; }
        public Nullable<System.DateTime> SUBMISSION_DT_TM { get; set; }
    
        public virtual User USER { get; set; }
    }
}
